export const destinations = [
  { value: "paris", label: "Paris" },
  { value: "bali", label: "Bali" },
  { value: "maldives", label: "Maldives" },
  { value: "santorini", label: "Santorini" },
  { value: "kyoto", label: "Kyoto" },
  { value: "rome", label: "Rome" },
  { value: "venice", label: "Venice" },
  { value: "cape-town", label: "Cape Town" },
  { value: "queenstown", label: "Queenstown" },
  { value: "machu-picchu", label: "Machu Picchu" },
  { value: "barcelona", label: "Barcelona" },
  { value: "dubai", label: "Dubai" },
  { value: "new-york", label: "New York" },
  { value: "tokyo", label: "Tokyo" },
  { value: "sydney", label: "Sydney" },
  { value: "amsterdam", label: "Amsterdam" },
  { value: "prague", label: "Prague" },
  { value: "venice", label: "Venice" },
  { value: "banff", label: "Banff" },
  { value: "florence", label: "Florence" },
  { value: "istanbul", label: "Istanbul" },
  { value: "london", label: "London" },
  { value: "rio-de-janeiro", label: "Rio de Janeiro" },
  { value: "são-paulo", label: "São Paulo" },
  { value: "los-angeles", label: "Los Angeles" },
  { value: "singapore", label: "Singapore" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "cairo", label: "Cairo" },
  { value: "beijing", label: "Beijing" },
  { value: "marrakech", label: "Marrakech" },
  { value: "edinburgh", label: "Edinburgh" },
  { value: "vienna", label: "Vienna" },
  { value: "seoul", label: "Seoul" },
  { value: "mexico-city", label: "Mexico City" },
  { value: "moscow", label: "Moscow" },
  { value: "lisbon", label: "Lisbon" },
  { value: "budapest", label: "Budapest" },
  { value: "zurich", label: "Zurich" },
  { value: "toronto", label: "Toronto" },
  { value: "san-francisco", label: "San Francisco" },
  { value: "athens", label: "Athens" },
  { value: "kruger-park", label: "Kruger National Park" },
];
